preppal-fe/src/pages/login.tsx
Front end user login page
Still need to add logic for actual login.
Test:
In app.tsx
Add `import Login from './pages/login';`
Replace `<Home></Home>` with `<LoginPage/>`
=> User Login page

preppal-fe/package-lock.json, preppal-fe/package.json, preppal-fe/src/app.tsx, preppal-fe/src/components/navbar/navbar.tsx
Setting up some routing for page navigation.
Added login button to NavBar. This should be temp where we add some logic to show either Login or Profile depending if the user is logged in.
May need to `npm install` to get the new packages.
=> Initial Routing for Page Navigation

preppal-be/app.ts, preppal-be/models/recipe.ts, preppal-be/models/user.ts, preppal-be/package-lock.json, preppal-be/package.json, preppal-be/routes/userApi.ts, preppal-be/server.ts
Added functionality to create a user.
How to test:
1. `cd preppal-be` and `npm start`
2. Use Postman to test to see if you are connected: do a `GET` request by using URL: `localhost:9001/api/user`
3. Open a new tab and do a `POST` request with URL `localhost:9001/api/users/createUser`, use header `Context-Type` with value `application/json`
4. In body, switch to text and select JSON 
``` { "username": "anyUsername", "password": "anyPassword" }```
=> Implement API to create a user

preppal-be/app.ts, preppal-be/configs/secrets.ts, preppal-be/package-lock.json, preppal-be/package.json, preppal-be/routes/authApi.ts, preppal-be/routes/userApi.ts
Added new API for login and get user info.
GET `/api/auth`  is the same as GET `/api/users`
POST `/api/auth` needs takes in username, password
GET `/api/users/lookup/:username` 
Uses "token" for persistent login or something.
To do:
encryption for passwords
=> Created API for login and to get user info

preppal-be/package-lock.json, preppal-be/routes/authApi.ts, preppal-be/routes/userApi.ts, preppal-fe/src/pages/login.tsx, preppal-fe/src/pages/signup.tsx
The front end now receives input and can send a http request to the back end
=> connect front back end for login

preppal-fe/package-lock.json, preppal-fe/package.json, preppal-fe/src/app.tsx, preppal-fe/src/components/navbar/navbar.tsx, preppal-fe/src/pages/new-recipe.tsx
=> Recipe creation page

preppal-be/models/user.ts, preppal-be/routes/userApi.ts
Added API to update user
POST: `/api/updateUser`
Body:
```
{
"_id": "65c957143e7703adde8850d6",
"username": "test11",
"password": "test11",
"bio": "Hi! THIS IS A TEST",
"ownRecipes": [
"65c9571e3e7703adde8850d9",
"65c957243e7703adde8850de"
],
"savedRecipes": [],
"following": []
}
```
Edit: removed friends from schema
=> Added API to update User

preppal-be/routes/recipeApi.ts
small bug fix
change string manipulation to replace all spaces with '-'
=> bug fix, replace to replaceAll

preppal-be/models/recipe.ts, preppal-be/models/user.ts, preppal-be/routes/recipeApi.ts
Schema update includes visibility and tags.
Recipe API has error handling logic and bug fix.
=> Update Recipe Schema and RecipeAPI

package-lock.json, package.json, preppal-be/configs/db.ts, preppal-be/configs/jest.config.ts, preppal-be/package-lock.json, preppal-be/package.json, preppal-be/routes/authApi.ts, preppal-be/routes/recipeApi.ts, preppal-be/routes/userApi.ts, preppal-be/tests/authApi.test.ts, preppal-be/tests/recipeApi.test.ts, preppal-be/tests/userApi.test.ts
Initial unit tests for our back end.
1. In dir `preppal-be` type `npm install`
2. `npm test` to run tests.
```Test Suites: 3 passed, 3 total                                                                                                                                                                                    
Tests:       48 passed, 48 total
Snapshots:   0 total
Time:        7.715 s
```
=> Unit Tests - User, Auth, Recipe

.github/workflows/preppal-be-tests.yml, .github/workflows/preppal-fe-tests.yml, preppal-fe/src/__tests__/pages/login.test.tsx, preppal-fe/src/__tests__/pages/signup.test.tsx, preppal-fe/src/pages/login.tsx, preppal-fe/src/pages/signup.tsx
CI Implementation for running tests.
Still need to figure out autobuild.
edit: simple front end tests added.
=> CI Implementation for Tests

preppal-be/auth/authorization.ts, preppal-be/routes/authApi.ts, preppal-be/routes/userApi.ts, preppal-be/tests/authApi.test.ts, preppal-fe/src/__tests__/pages/collections.test.tsx, preppal-fe/src/app.tsx, preppal-fe/src/components/nav-bar/nav-bar.css, preppal-fe/src/pages/collections.tsx, preppal-fe/src/pages/home.tsx, preppal-fe/src/styles/global.css
Collections page layout and functionality. 
Removed "Testing my recipes" 
Favourites/saved recipes have not been implemented
Will probably clean up the styling later
=> collections page layout

documentation/sequence-diagrams/explore.md, documentation/sequence-diagrams/login.md, documentation/sequence-diagrams/new-recipe.md, documentation/sequence-diagrams/signup.md
sequence diagrams for login and sign up
see: https://github.com/algorizan/PrepPal/tree/hwbit/sequence-diagrams-login-signup/documentation/sequence-diagrams
please confirm if it is accurate to your portion
edit: added new recipe and explore
=> sequence diagrams for login and signup

.github/workflows/preppal-be-tests.yml, .github/workflows/preppal-build.yml, .github/workflows/preppal-fe-tests.yml, preppal-fe/package-lock.json, preppal-fe/package.json, preppal-fe/src/pages/collections.tsx
=> Implement CI for building frontend

.eslintrc.js, preppal-fe/src/pages/collections.tsx, preppal-fe/src/pages/profile.tsx
=> Revert "Turned off eslint warning that appears for unknown reasons."

preppal-be/routes/recipeApi.ts, preppal-fe/src/app.tsx, preppal-fe/src/components/nav-bar/nav-bar.tsx, preppal-fe/src/pages/home.tsx, preppal-fe/src/pages/search.tsx, preppal-fe/src/styles/global.css
Searching recipes by title through the Search bar at the top of the website.
=> Searching recipes

preppal-fe/src/app.tsx, preppal-fe/src/pages/edit-profile.tsx, preppal-fe/src/pages/profile.tsx
+Added logic to edit-profile page to allow a user to edit their stored values (Password and Bio).
=> Created edit-profile page and routing

documentation/sequence-diagrams/calendar.md, documentation/sequence-diagrams/collections.md, documentation/sequence-diagrams/comments.md, documentation/sequence-diagrams/recipe.md, documentation/sequence-diagrams/search.md, documentation/sequence-diagrams/shopping-list.md
Complete sequence diagrams for all planned features.
=> Sequence Diagram Batch

preppal-fe/src/__tests__/pages/login.test.tsx, preppal-fe/src/app.tsx, preppal-fe/src/components/nav-bar/nav-bar.tsx, preppal-fe/src/pages/collections.tsx, preppal-fe/src/pages/edit-profile.tsx, preppal-fe/src/pages/home.tsx, preppal-fe/src/pages/login.tsx, preppal-fe/src/pages/new-recipe.tsx, preppal-fe/src/pages/profile.tsx, preppal-fe/src/pages/recipe.tsx, preppal-fe/src/pages/search.tsx, preppal-fe/src/pages/signup.tsx
Removed NavBar from app.tsx.
Removed unused remember me checkbox.
Updated frontend login tests.
=> Moved NavBar into all pages.

preppal-be/models/recipe.ts, preppal-be/routes/recipeApi.ts, preppal-be/tests/recipeApi.test.ts, preppal-fe/src/pages/collections.tsx, preppal-fe/src/pages/edit-profile.tsx, preppal-fe/src/pages/new-recipe.tsx
Updated collections.tsx to map all recipes, not just public for MyRecipes. 
Removed change profile pic label in edit-profile.tsx. 
Updated recipeApi.ts to require isPublic.
Updated recipe.ts to require isPublic.
Fixed recipeApi.test.ts test by adding isPublic to all tests.
=> Added checkbox on new-recipe.tsx to set isPublic.

README.md, documentation/instructions.md
Instructions on how to run the application.
=> Instructions to run applications

preppal-be/models/comments.ts
MongoDB schema for reviews, comments, and ratings
=> MongoDB schema for reviews, comments, rating

preppal-fe/src/components/nav-bar/nav-bar.tsx, preppal-fe/src/pages/collections.tsx, preppal-fe/src/pages/edit-profile.tsx, preppal-fe/src/pages/login.tsx, preppal-fe/src/pages/new-recipe.tsx, preppal-fe/src/pages/profile.tsx, preppal-fe/src/pages/signup.tsx
A new sessionStorage will be used every time a new tab or window is opened. This requires the user to login every time, but this is probably better than dealing with localStorage that is not cleared when the tab or window is closed. This will fix the issue when the app is in a logged in state even though user session token has been expired
=> Use sessionStorage instead of localStorage

preppal-be/routes/recipeApi.ts, preppal-be/tests/recipeApi.test.ts, preppal-fe/src/__tests__/pages/search.test.tsx, preppal-fe/src/pages/search.tsx
This fixes search not rerendering when querying again
=> Bug fix: second search query

preppal-fe/src/pages/recipe.tsx
=> Shows Rating for a Recipe

preppal-be/routes/userApi.ts, preppal-be/tests/userApi.test.ts, preppal-fe/src/components/recipe-catalog/recipe-catalog.tsx, preppal-fe/src/pages/collections.tsx, preppal-fe/src/pages/home.tsx, preppal-fe/src/pages/profile.tsx, preppal-fe/src/pages/recipe.tsx, preppal-fe/src/pages/search.tsx, preppal-fe/src/utils/date.ts
When viewing a profile that is not your own, you will see the user's public recipes
=> change profile display

preppal-be/tests/userApi.test.ts
this is to fix a test with updated user info
=> fix test with updated user

.github/workflows/preppal-docker-publish.yml, .github/workflows/preppal-fe-azure-deploy.yml, docker-compose.yml, preppal-be/.dockerignore, preppal-be/Dockerfile, preppal-fe/.dockerignore, preppal-fe/Dockerfile
in root dir: `docker-compose up -d`
`localhost:3000` in browser
=> Docker Deploy

preppal-be/routes/recipeApi.ts, preppal-be/tests/recipeApi.test.ts, preppal-fe/src/app.tsx, preppal-fe/src/components/filter-menu/filter-menu.css, preppal-fe/src/components/filter-menu/filter-menu.tsx, preppal-fe/src/components/nav-bar/nav-bar.css, preppal-fe/src/components/nav-bar/nav-bar.tsx, preppal-fe/src/pages/search.tsx, preppal-fe/src/styles/global.css, preppal-fe/src/styles/search.css
Added a clear button to the search bar, as well as a search button that will take you to the Search Page.
In the Search Page, I added a Filter button that will open up a Filter Menu where you can input advanced filter parameters and search recipes that match all of those criteria.
=> Search Filters

preppal-be/routes/userApi.ts, preppal-be/tests/userApi.test.ts, preppal-fe/public/index.html, preppal-fe/public/manifest.json, preppal-fe/src/__tests__/pages/edit-profile.test.tsx, preppal-fe/src/__tests__/pages/profile.test.tsx, preppal-fe/src/__tests__/pages/recipe.test.tsx, preppal-fe/src/__tests__/pages/signup.test.tsx, preppal-fe/src/components/follow-button/follow-button.tsx, preppal-fe/src/components/nav-bar/nav-bar.tsx, preppal-fe/src/pages/profile.tsx, preppal-fe/src/pages/recipe.tsx
Created endpoints for following, unfollowing, and checking follow status
Added follow button and check for login status to profile page
Wrote and fixed tests
Fixed a couple bugs
Rename app to PrepPal
=> Follow function

.github/workflows/preppal-fe-azure-deploy.yml
It might mess with secrets when we merge to main.
=> Change Azure FE deploy branch.

preppal-be/routes/recipeApi.ts, preppal-be/routes/reviewApi.ts, preppal-be/tests/reviewApi.test.ts, preppal-fe/src/pages/create-recipe.tsx
=> Fix comment but to allow new reviews on newly created recipes

preppal-be/package-lock.json, preppal-fe/jest.config.js, preppal-fe/src/__tests__/pages/profile.test.tsx, preppal-fe/src/pages/login.tsx, preppal-fe/src/pages/profile.tsx, preppal-fe/src/pages/recipe.tsx
Console error no longer exists
Also made it so that it requires one api call to get info
=> fix profile console error bug

jmeter/testing_results.csv, jmeter/testing_summary.csv, jmeter/testplan.jmx, preppal-fe/public/index.html, testplan.jmx
This is for the load testing script.
We are using JMeter. 
This script will make 200 requests per min by 20 users (~10 requests per min by each user).
There are 10 different api calls used in the script (the ones that would populate the database were not included)
Need to download jmeter to use gui to run tests
=> Load testing script

preppal-fe/src/pages/recipe.tsx
Because setUsername is async, it will not be set before all the rendering. We should make useEffect dependent on username
=> fix for setting username async

preppal-fe/src/__tests__/pages/profile.test.tsx
Just need to change one of the test names
=> update test name
